app/items/controllers.py
from flask_sqlalchemy import SQLAlchemy
from flask import Flask, render_template, request, flash,redirect
from flask import Blueprint, request, render_template,flash, g, session, redirect, url_for,jsonify
from functools import wraps
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import LoginManager, login_user, logout_user, login_required, current_user,UserMixin
from io import BytesIO
from PIL import Image
from app import db
import os
from flask_mail import Message
from app import mail
from config import ADMINS
from app.users.models import User
from app.items.models import Item
from app.cart.models import Cart
from app.tags.models import Tags
from app.notifications.models import Notif
mod_selleritems = Blueprint('sellertable', __name__, url_prefix = '/sellertable')


@mod_selleritems.route('/additem',methods=['GET','POST'])
def addItem():
	if not g.user.is_authenticated or g.user.buyerseller == 0:
		return "You need to login as a seller for accessing this."
	if request.method=='POST':
		name = request.form['name']
		quantity = request.form['quantity']
		imageurl=""
		price = int(request.form['price'])
		description = request.form['description']
		specifications = request.form['specifications']
		img= request.files['photo']
		shipping = request.form['shipping']
		tags = request.form['tags']
		category=request.form['category']
		sellerid = g.user.id
		s=Item(name,imageurl,quantity,price,description,specifications,sellerid,shipping,category)
		db.session.add(s)
		db.session.commit()
		taglist=tags.split(' ')
		for i in range(len(taglist)):
			t = Tags(tagcontent=taglist[i],itemid=s.id)
			db.session.add(t)
			db.session.commit()


		img = Image.open(img)
		dir=os.getcwd()
		dir1= os.path.join(dir,'app/static/')
		filename = str(s.id)+'.jpg'
		imageurl = dir1+ filename
		print(imageurl)
		img.save(imageurl)
		print("YO")
		item = Item.query.filter(Item.id == s.id).first()
		item.imageurl = filename
		print(item.imageurl)
		print(s.id)
		db.session.commit()
		cartproduct = Cart(itemid=s.id,userid=g.user.id,quantity=quantity)
		db.session.add(cartproduct)
		db.session.commit()
	
		print(s.id)
		return redirect(url_for('.sellertable'))

	else:
		return render_template("itementryform.html")




def send_email(subject, sender, recipients, text_body):
    msg = Message(subject, sender=sender, recipients=recipients)
    msg.body = text_body
    mail.send(msg)


@mod_selleritems.route("/update",methods=["POST"])
def updatequantity():
	if request.method=="POST" and g.user.is_authenticated and g.user.buyerseller:
		itemid = request.form['itemid']
		print(itemid)
		quanti= request.form['quantity']
		item = Item.query.filter(Item.id == itemid).first()
		if (item.quantity <= 0):
			users = Notif.query.filter( Notif.itemid == itemid).all()
			for i in users:	
				user = User.query.filter(User.id == i.userid).first()
				print(user.email)
				send_email("The item you wished for is now available" ,ADMINS[0],ADMINS,"YO")

		item.quantity=quanti
		db.session.commit();
		return "Successfully updated items in your cart!"
	else:
		return "Please login to continue"

@mod_selleritems.route("/getitems",methods=["GET"])
def get_all_items():
	if request.method=="GET" and g.user.is_authenticated and g.user.buyerseller:
		it = Item.query.all()
		allitems={ "items" : []}
		for i in it:
	  		print(i.imageurl)
	  		allitems["items"].append(i.itemSerialize())

		return jsonify(allitems)


@mod_selleritems.route("",methods=["GET"])
def sellertable():
	if g.user.is_authenticated and g.user.buyerseller == 1:
		return render_template('sellertable.html')
	else:
		return "Sorry you are not authorized to access this page"
		

@mod_selleritems.route("/categorytable/<typ>",methods=['GET'])
def categorytable(typ):
	if request.method == 'GET':
		print(typ)
		item=Item.query.filter(Item.category == typ).all()
		allcategory=[]
		for i in item:
			allcategory.append(i.itemSerialize())
		print(allcategory)
	return render_template('categorytable.html',allcategory=allcategory)

app/users/controllers.py
from flask import Blueprint, request, render_template,flash, g, session, redirect, url_for
from app import db,login_manager
from flask_cors import CORS
from flask_bootstrap import Bootstrap
from flask_wtf import FlaskForm
from flask_login import LoginManager, login_user, logout_user, login_required, current_user,UserMixin
from sqlalchemy import and_
from app.users.models import User
from app.users.forms import RegistrationForm,LoginForm
mod_users = Blueprint('users', __name__, url_prefix='')


@login_manager.user_loader
def load_user(user_id):
	return  User.query.get(int(user_id))



@mod_users.route('/')
def home():
	return render_template('index.html')


@mod_users.route('/signupBuyer', methods=['GET', 'POST'])
def registerBuyer():
	
	form=RegistrationForm()
	if request.method == 'POST':
		if form.validate()==False:
			flash('all fields are required')
			return render_template('register1.html',form=form)
		else:
			name=form.name.data
			email=form.email.data
			password=form.password.data
			try:
				buyer=User(name,email,password,0)
				db.session.add(buyer)
				db.session.commit()
				flash('You have successfully registered! You may now login.')
				return redirect(url_for('.loginBuyer'))
			except:
				error_mesg="User with given email already registered"
				print(error_mesg)
				return render_template('register1.html',form=form,error=error_mesg)
	else :

		return render_template('register1.html',form=form)


@mod_users.route('/signupSeller', methods=['GET', 'POST'])
def registerSeller():
	form=RegistrationForm()
	if request.method == 'POST':
		if form.validate()==False:
			flash('all field are required')
			return render_template('register1.html',form=form)
		else:

			name=form.name.data
			email=form.email.data
			password=form.password.data
			try:
				seller =User(name,email,password,1)
				db.session.add(seller)
				db.session.commit()
				print('gulshan')
				flash('You have successfully registered! You may now login.')
				return redirect(url_for('.loginSeller'))
			except:
				error_mesg="User with given email already registered"
				print(error_mesg)
				return render_template('register1.html',form=form,error=error_mesg)
	else :

		return render_template('register1.html',form=form) 


@mod_users.route('/loginBuyer',methods=['GET','POST'])
def loginBuyer():
	form=LoginForm(request.form)
	remember_me = False
	if form.validate_on_submit():
		if 'remember_me' in form:
			remember_me=True
		buyer = User.query.filter(and_(User.email==form.email.data,User.buyerseller==0)).first()
		if buyer  is not None and buyer.check_password(form.password.data):
			login_user(buyer,remember=remember_me)
			return redirect(url_for('.home'))
			
		else:
			if buyer is None:
				error_mesg="Invalid email . Please register yourself first."
			else:
				error_mesg="Invalid password . Please try again!'"
			return render_template('login.html',form=form,error=error_mesg)
	else:
		return render_template('login.html',form=form)



@mod_users.route('/loginSeller',methods=['GET','POST'])
def loginSeller():
	form=LoginForm(request.form)
	remember_me = False
	if form.validate_on_submit():
		if 'remember_me' in form:
			remember_me=True
		seller = User.query.filter(and_(User.email==form.email.data,User.buyerseller==1)).first()
		if seller  is not None and seller.check_password(form.password.data):
			login_user(seller,remember=remember_me)
			print("Logging user in")
			return redirect(url_for('.home'))
		else:
			if seller is None:
				error_mesg="Invalid email . Please register yourself first."
			else:
				error_mesg="Invalid password . Please try again!"
			return render_template('login.html',form=form,error=error_mesg)
	else:
		return render_template('login.html',form=form)


@mod_users.route('/logout')
def logout():
	if g.user.is_authenticated():
		logout_user()
		print("Reachedlogout")
		flash('You have successfully been logged out.')
		return redirect(url_for('.home'))
	else:
		return redirect(url_for('.home'))

app/templates/base.html
<!DOCTYPE html>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	 <!--<link href="css/bootstrap.min.css" rel="stylesheet">--> 
	 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link rel="stylesheet" href="{{ url_for('static', filename='base.css') }}">
   
	<style>
	.navbar
{
    margin-bottom: 0;
}
#search{
    width: 130px;
-webkit-transition: width 0.3s ease-in-out;
        transition: width 0.3s ease-in-out;
}
#search:focus{
        width: 150%;
}
</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
	   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% block head %}
       
	<title>
		{% block title %}{% endblock %}
	</title>
	{% endblock %}
    <script type=text/javascript>
        $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
    </script>
</head>


   <nav id="mainNav" class="navbar navbar-inverse">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header col-md-3">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="{{ url_for('users.home' ) }}">Home</a>
            </div>
                <div class="col-sm-3 col-md-3 col-md-6">     
        <form class="navbar-form" role="search" action="/tags/displayproducts" method="POST">
        <div class="input-group">
             <div class="input-group-btn">
                <button class="btn btn-default" type="submit" name="search-button"><i class="glyphicon glyphicon-search"></i></button>
            </div>
            <input type="text" class="form-control" placeholder="Search" name="tagstring" id="search">
           
        </div>
        </form>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="login">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="/#contact">Contact</a>
                    </li>

                {% if not g.user.is_authenticated %}
                    

                          <li class="dropdown">
        			<a href="#" class="dropdown-toggle" data-toggle="dropdown">Login
        			<span class="caret"></span></a>
       					 <ul class="dropdown-menu">
          <li><a href="{{ url_for('users.loginBuyer') }}">As a buyer</a></li>
          <li><a href="{{ url_for('users.loginSeller') }}">As a seller</a></li>
        </ul></li>




                          <li class="dropdown">
        			<a href="#" class="dropdown-toggle" data-toggle="dropdown">Register
        			<span class="caret"></span></a>
       					 <ul class="dropdown-menu">
          <li><a href="{{ url_for('users.registerBuyer') }}">As a buyer</a></li>
          <li><a href="{{ url_for('users.registerSeller') }}">As a seller</a></li>
        </ul></li>

                {% endif %}
                {% if g.user.is_authenticated %}


                    {% if g.user.buyerseller %}
                    <li>
                        <a class="page-scroll" href="{{ url_for('sellertable.sellertable') }}">Sell</a>
                    </li>
                    {% endif %}

                    {% if not g.user.buyerseller %}
                    <li>
                        <a class="page-scroll" href="{{ url_for('buyertable.buyertable') }}"><span class="glyphicon glyphicon-shopping-cart"></span>View Cart</a>
                    </li>
                    {% endif %}
                 <li>
                        <a class="page-scroll" href="{{ url_for('users.logout') }}">Logout</a>
                    </li>
                {% endif %}






                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    
    </nav>
    <body>
    <div id="content">
     
    {% block content %}{% endblock %}
    </div>

    


</body>
</html>

app/templates/buyertable.html
{% extends "base.html" %}
{% block title %}
This is the buyer's table
	
{% endblock %}
{% block head %}
<style>
table{
		width: 100%;
	}
td{
		padding: 15px;
		font-weight: 600;
}
.my{
		width: 300px;
		height: 40px;
}
.h{
		text-align: center;
		font-weight: 600;
	}
</style>
{% endblock %}

{% block content %}
<div class="container">
<div class="jumbotron">
<h2 class="h">MY CART ITEMS</h2>
<table>
	<tr>
		<td><h2><i> # </i></h2></td>
		<td><h2><i> Item name </i></h2></td>
		<td><h2><i> Quantity  </i></h2></td>
		<td></td>
	</tr>
	<br/><br/>
	<br/>
	<tbody id="itemtable">
	</tbody>
</table>
<br/><br/>
<p id="message"></p>
<br/>
<br/><br/><br/>

<table>
<tr>
<td style="width: 50%;">
<button type="submit" id="update-item-button" value="UPDATE" class="btn btn-primary my">UPDATE</button>
</td><td>
<button type="submit" id ="buy-button" value="BUY" class="btn btn-primary my">BUY</button>
</td></tr></table>
</div>
</div>
{% block javascript %}
    <script type="text/javascript">
        {% include "buyertable.js" %}
    </script>
    <!-- The contents of myscript.js will be loaded inside the script tag -->
{% endblock %}

{% endblock %}

app/templates/homepage.html
<!DOCTYPE html>
<html>
<head>
	<title>
		This is the home page
	</title>
	 <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
<script type="text/javascript" src="homepage.js"></script> 
<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<div class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#home">Home</a></li>
      <li><a href="#contact">Contact</a></li>
      <li><a href="#Register">Register</a></li>
      <li><a href="#login">Login</a></li>
    </ul>
  </div>
</div>

<div id="content">
Hello
</div>
</body>
</html>

app/templates/index.html
{% extends "base.html" %}
{% block title %}

		The home page

{% endblock %}
{% block content %}
{% block head %}
<style>
.imag{
    width: 300px;
    height: 200px;

}
.img-circle{
    width:160px;
    height:160px;
}
div.gallery {
        border: 1px solid #ccc;
}

div.gallery:hover {
        border: 1px solid #777;
}

div.gallery img{
        width: 100%;
        height:70%;
}
</style>
{% endblock %}
    <div class="responsive">
    <div class="gallery">
    	<img src="{{ url_for('static', filename = 'best-shopping.jpg') }}" class="img-responsive">

    </div> 		
    </div>




       <section id="category" class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Category</h2>
                    <h3 class="section-subheading text-muted"> Enter Into World Of Items</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 col-sm-6 portfolio-item">
                    <a href= "{{ url_for('sellertable.categorytable' , typ ='electrical_appliance') }}" class="portfolio-link" data-toggle="modal">
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <i class="fa fa-plus fa-3x"></i>
                            </div>
                        </div>
                        <img src="{{ url_for('static', filename = 'appliances.jpg') }}" class="img-responsive imag" alt="">
                    </a>
                    <div class="portfolio-caption">
                        <h4>Electrical Appliances</h4>
                        <p class="text-muted">Electronics World</p>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 portfolio-item">
                    <a href= "{{ url_for('sellertable.categorytable' , typ = 'clothing' )}}" class="portfolio-link" data-toggle="modal">
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <i class="fa fa-plus fa-3x"></i>
                            </div>
                        </div>
                        <img src="{{ url_for('static', filename = 'clothing.jpg') }}" class="img-responsive imag" alt="">
                    </a>
                    <div class="portfolio-caption">
                        <h4>Shirt,jeans,T-shirt etc.</h4>
                        <p class="text-muted">Cloth World</p>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 portfolio-item">
                    <a href= "{{ url_for('sellertable.categorytable' , typ = 'footwear') }}" class="portfolio-link" data-toggle="modal">
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <i class="fa fa-plus fa-3x"></i>
                            </div>
                        </div>
                        <img src="{{ url_for('static', filename = 'footwear.jpg') }}" class="img-responsive imag" alt="">
                    </a>
                    <div class="portfolio-caption">
                        <h4>Shoes,Sports,Sandal</h4>
                        <p class="text-muted">Footwear World</p>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 portfolio-item">
                    <a href= "{{ url_for('sellertable.categorytable' , typ = 'Gadgets') }}" class="portfolio-link" data-toggle="modal">
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <i class="fa fa-plus fa-3x"></i>
                            </div>
                        </div>
                        <img src="{{ url_for('static', filename = 'gadgets.jpg') }}" class="img-responsive imag" alt="">
                    </a>
                    <div class="portfolio-caption">
                        <h4>Mobile,laptop,iphone,ipad</h4>
                        <p class="text-muted">Gadgets World</p>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 portfolio-item">
                    <a href="{{ url_for('sellertable.categorytable' , typ = 'Sports') }}" class="portfolio-link" data-toggle="modal">
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <i class="fa fa-plus fa-3x"></i>
                            </div>
                        </div>
                        <img src="{{ url_for('static', filename = 'sport.jpg') }}" class="img-responsive imag" alt="">
                    </a>
                    <div class="portfolio-caption">
                        <h4>Cricket,hockey,Tennis,Football</h4>
                        <p class="text-muted">Sports World</p>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 portfolio-item">
                    <a href="{{ url_for('sellertable.categorytable' , typ = 'Kitchenitems') }}" class="portfolio-link" data-toggle="modal">
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <i class="fa fa-plus fa-3x"></i>
                            </div>
                        </div>
                        <img src="{{ url_for('static', filename = 'kitchen.jpg') }}" class="img-responsive imag" alt="">
                    </a>
                    <div class="portfolio-caption">
                        <h4>Glasses,Plates,Crockery,Jug....</h4>
                        <p class="text-muted">Kitchen World</p>
                    </div>
                </div>
            </div>
        </div>
    </section>


    </div>
    <br><br><br><br><br>
    <!-- Developer -->
    <section id="developer" class="bg-light-gray">
        <div class="container">
            <div class="row">
                    <h2 class="section-heading" style="text-align: left;">Developed By</h2>
            </div>
            <br><br>
            <div>
                <div>
                    <div class="creator">
                        <div class="row">
                            <div class="col-md-4 col-sm-6">
                        <img src="{{ url_for('static', filename = 'gulshanmittal.jpg') }}" class="img-responsive img-circle" alt="">
                        <h4>Gulshan Mittal</h4>
                        <p class="text-muted">Developer</p>
                        </div>
                        <div class="col-md-4 col-sm-6">
                        <img src="{{ url_for('static', filename = 'nirvan.jpg') }}" class="img-responsive img-circle" alt="">
                        <h4>Nirvan Singhania</h4>
                        <p class="text-muted">Developer</p>
                        </div>
                        <div class="col-md-4 col-sm-6">
                        <img src="{{ url_for('static', filename = 'yash.jpg') }}" class="img-responsive img-circle" alt="">
                        <h4>Yash Agarwal</h4>
                        <p class="text-muted">Developer</p>
                        </div>
                        </div>

                        <ul class="list-inline social-buttons">
                            <li><a href="#"><i class="fa fa-twitter"></i></a>
                            </li>
                            <li><a href="#"><i class="fa fa-facebook"></i></a>
                            </li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
   <br><br><br><br><br>

    <div class="jumbotron">
     <br><br><br>
    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Contact Us</h2>
                    <h3 class="section-subheading text-muted">Shopping Portal Team</h3>
                </div>
            </div>
            <br><br>
            <div class="row">
                <div class="col-lg-12">
                    <form name="sentMessage" id="contactForm" validate >
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Your Name *" id="name" required data-validation-required-message="Please enter your name." style="border-color: green">
                                    <p class="help-block text-danger"></p>
                                </div>
                                <div class="form-group">
                                    <input type="email" class="form-control" placeholder="Your Email *" id="email" required data-validation-required-message="Please enter your email address." style="border-color: green">
                                    <p class="help-block text-danger"></p>
                                </div>
                                <div class="form-group">
                                    <input type="tel" class="form-control" placeholder="Your Phone *" id="phone" required data-validation-required-message="Please enter your phone number." style="border-color: green">
                                    <p class="help-block text-danger"></p>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <textarea class="form-control" placeholder="Your Message *" id="message" style="border-color: green"></textarea>
                                    <p class="help-block text-danger"></p>
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="col-lg-12 text-center">
                                <div id="success"></div>
                                <button type="button" class="btn btn-primary" class=>Send Message</button>  <!-- need to be change -->
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <br><br><br><br>
    </div>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <span class="copyright">Copyright &copy; Our Website 2017</span>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline social-buttons">
                        <li><a href="#"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <ul class="list-inline quicklinks">
                        <li><a href="#">Privacy Policy</a>
                        </li>
                        <li><a href="#">Terms of Use</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
{% endblock %}

app/templates/index2.html
{% extends "base.html" %}
{% block title %}

		The home page

{% endblock %}
{% block content %}

  
    
    
    	<img src="{{ url_for('static', filename = 'best-shopping.jpg') }}" class="img-responsive">

    	


       <section id="portfolio" class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Portfolio</h2>
                    <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 col-sm-6 portfolio-item">
                    <a href= "{{ url_for('sellertable.categorytable' , typ ='electrical_appliance') }}" class="portfolio-link" data-toggle="modal">
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <i class="fa fa-plus fa-3x"></i>
                            </div>
                        </div>
                        <img src="{{ url_for('static', filename = '1.jpg') }}" class="img-responsive" alt="">
                    </a>
                    <div class="portfolio-caption">
                        <h4>Round Icons</h4>
                        <p class="text-muted">Graphic Design</p>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 portfolio-item">
                    <a href= "{{ url_for('sellertable.categorytable' , typ = 'clothing' )}}" class="portfolio-link" data-toggle="modal">
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <i class="fa fa-plus fa-3x"></i>
                            </div>
                        </div>
                        <img src="{{ url_for('static', filename = '1.jpg') }}" class="img-responsive" alt="">
                    </a>
                    <div class="portfolio-caption">
                        <h4>Startup Framework</h4>
                        <p class="text-muted">Website Design</p>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 portfolio-item">
                    <a href= "{{ url_for('sellertable.categorytable' , typ = 'footwear') }}" class="portfolio-link" data-toggle="modal">
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <i class="fa fa-plus fa-3x"></i>
                            </div>
                        </div>
                        <img src="{{ url_for('static', filename = '1.jpg') }}" class="img-responsive" alt="">
                    </a>
                    <div class="portfolio-caption">
                        <h4>Treehouse</h4>
                        <p class="text-muted">Website Design</p>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 portfolio-item">
                    <a href= "{{ url_for('sellertable.categorytable' , typ = 'Gadgets') }}" class="portfolio-link" data-toggle="modal">
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <i class="fa fa-plus fa-3x"></i>
                            </div>
                        </div>
                        <img src="{{ url_for('static', filename = '1.jpg') }}" class="img-responsive" alt="">
                    </a>
                    <div class="portfolio-caption">
                        <h4>Golden</h4>
                        <p class="text-muted">Website Design</p>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 portfolio-item">
                    <a href="#portfolioModal5" class="portfolio-link" data-toggle="modal">
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <i class="fa fa-plus fa-3x"></i>
                            </div>
                        </div>
                        <img src="{{ url_for('static', filename = '1.jpg') }}" class="img-responsive" alt="">
                    </a>
                    <div class="portfolio-caption">
                        <h4>Escape</h4>
                        <p class="text-muted">Website Design</p>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 portfolio-item">
                    <a href="#portfolioModal6" class="portfolio-link" data-toggle="modal">
                        <div class="portfolio-hover">
                            <div class="portfolio-hover-content">
                                <i class="fa fa-plus fa-3x"></i>
                            </div>
                        </div>
                        <img src="{{ url_for('static', filename = '1.jpg') }}" class="img-responsive" alt="">
                    </a>
                    <div class="portfolio-caption">
                        <h4>Dreams</h4>
                        <p class="text-muted">Website Design</p>
                    </div>
                </div>
            </div>
        </div>
    </section>


    </div>
{% endblock %}